services:
    - docker

language: php

cache:
    directories:
        - $HOME/.composer/cache
        - $HOME/phpcs-cache

php:
    - 7.1
    - 7.2
    - 7.3
    - 7.4

matrix:
    include:
        -   php: 7.4
            env: CODING_STANDARD=1 PHPSTAN=1

install:
    - docker-compose up -d elastic
    - docker-compose up -d web
    - docker-compose exec web make composer

script:
    - if [ "$PHPSTAN" = "1" ]; then docker-compose exec web make phpstan; fi
    - if [ "$CODING_STANDARD" = "1" ]; then docker-compose exec web make cs; fi
    - docker-compose exec web make tests
