language: php

os: linux

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/phpcs-cache

php:
 - "7.1"
 - "7.2"
 - "7.3"

jdk:
  - oraclejdk8

env:
  matrix:
#    - RUN_TESTS=1 ES_VERSION="2.4.6"
    - RUN_TESTS=1 ES_VERSION="5.6.15"
    - RUN_TESTS=1 ES_VERSION="6.7.1"
    - RUN_TESTS=1 ES_VERSION="7.0.0-linux-x86_64"

matrix:
  include:
    - php: 7.3
      env: CODING_STANDARD=1 PHPSTAN=1

before_install:
  - travis_retry composer self-update
  - sudo apt-get update && sudo apt-get install oracle-java8-installer
  - java -version
  - sudo update-alternatives --set java /usr/lib/jvm/java-8-oracle/jre/bin/java
  - java -version
  - ./travis-elastic.sh

install:
  - travis_retry composer update --no-interaction --no-suggest --no-progress --prefer-dist --prefer-stable

script:
  - if [ "$PHPSTAN" = "1" ]; then vendor/bin/phpstan analyse -l 7 -c phpstan.neon src tests; fi
  - if [ "$CODING_STANDARD" = "1" ]; then vendor/bin/phpcs --standard=vendor/spameri/coding-standard/src/ruleset.xml --cache=$HOME/phpcs-cache/.phpcs-cache src tests; fi
  - if [ "$RUN_TESTS" = "1" ]; then vendor/bin/tester $COVERAGE -s -c ./tests/php.ini ./tests; fi
